# pull official base image
FROM node:16.14.2-alpine

# set working directory
WORKDIR /server

# add `/app/node_modules/.bin` to $PATH 
ENV PATH /server/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install

# add app
COPY /api /server

# start app
CMD ["node", "server.js"]